databases:
  - name: cert-checker-db
    databaseName: cert_checker
    user: cert_checker_user

services:
  - type: web
    name: cert-checker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cert_checker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cert-checker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False