# Generated by Django 5.2.4 on 2025-07-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН организации')),
                ('address', models.TextField(verbose_name='Адрес организации')),
                ('certificate_number_part', models.CharField(max_length=5, verbose_name='Номер сертификата (часть)')),
                ('iso_standard_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование стандарта в сертификате')),
                ('quality_management_system', models.TextField(verbose_name='Система менеджмента качества')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания действия')),
                ('status', models.CharField(choices=[('active', 'Действителен'), ('inspection_failed', 'Действие сертификата приостановлено, не пройден инспекционный контроль'), ('expired', 'Действие сертификата приостановлено, истек срок действия'), ('revoked', 'Отозван'), ('pending', 'В ожидании')], default='active', max_length=20, verbose_name='Статус')),
                ('first_inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата 1-го инспекционного контроля')),
                ('first_inspection_status', models.CharField(choices=[('pending', 'Ожидается в будущем'), ('passed', 'Пройден'), ('failed', 'Не пройден')], default='pending', max_length=10, verbose_name='Статус 1-го инспекционного контроля')),
                ('second_inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата 2-го инспекционного контроля')),
                ('second_inspection_status', models.CharField(choices=[('pending', 'Ожидается в будущем'), ('passed', 'Пройден'), ('failed', 'Не пройден')], default='pending', max_length=10, verbose_name='Статус 2-го инспекционного контроля')),
                ('file1', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата')),
                ('file2', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл приложения')),
                ('file3', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Дополнительный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('validity_period', models.IntegerField(choices=[(1, '1 год'), (2, '2 года'), (3, '3 года')], default=1, verbose_name='Срок действия')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Уведомления подключены')),
                ('certification_area', models.TextField(verbose_name='Область сертификации')),
                ('generated_permission', models.FileField(blank=True, null=True, upload_to='permissions/', verbose_name='Сгенерированное разрешение')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ISOStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=100, verbose_name='Стандарт ИСО')),
                ('description', models.TextField(verbose_name='Расшифровка стандарта')),
                ('certificate_number_prefix', models.CharField(max_length=50, verbose_name='Префикс в сертификате')),
                ('certificate_standard_name', models.CharField(max_length=255, verbose_name='Наименование стандарта в сертификате')),
            ],
            options={
                'verbose_name': 'Стандарт ИСО',
                'verbose_name_plural': 'Стандарты ИСО',
                'ordering': ['standard_name'],
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО аудитора')),
                ('audit_file', models.FileField(blank=True, null=True, upload_to='audit_files/', verbose_name='Файл аудита')),
                ('audit_number', models.CharField(blank=True, max_length=20, verbose_name='Номер аудита')),
                ('generated_audit_image', models.ImageField(blank=True, null=True, upload_to='audit_images/')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditors', to='certificates.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='iso_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.isostandard', verbose_name='Стандарт ISO'),
        ),
    ]
