# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number_part',
            field=models.CharField(max_length=5, unique=True, verbose_name='Номер сертификата (часть)'),
        ),
    ]
