# Generated by Django 5.2.4 on 2025-07-29 08:33

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    for row in Certificate.objects.all():
        row.unique_identifier = uuid.uuid4()
        row.save(update_fields=['unique_identifier'])

class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='certificate',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='certificate',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]