# Generated by Django 5.2.4 on 2025-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='unique_identifier',
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
