# Generated by Django 5.2.4 on 2025-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_remove_certificate_unique_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file1_svg',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
