# Generated by Django 5.2.4 on 2025-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_file1_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='audit_file_svg',
            field=models.FileField(blank=True, null=True, upload_to='audit_files/', verbose_name='Файл аудита (SVG)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_svg',
            field=models.FileField(blank=True, null=True, upload_to='permissions/', verbose_name='Разрешение (SVG)'),
        ),
    ]
