# Generated by Django 5.2.4 on 2025-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_auditor_audit_file_svg_certificate_file2_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
