# Generated by Django 5.2.4 on 2025-07-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_certificate_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='audit_file_svg',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file1_svg',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file2_svg',
        ),
        migrations.AddField(
            model_name='auditor',
            name='audit_file_psd',
            field=models.FileField(blank=True, null=True, upload_to='audit_files/', verbose_name='Файл аудита (PSD)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file1_psd',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат (PSD)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_psd',
            field=models.FileField(blank=True, null=True, upload_to='permissions/', verbose_name='Разрешение (PSD)'),
        ),
    ]
