# Generated by Django 5.2.4 on 2025-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_remove_auditor_audit_file_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file1_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file1_psd_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_psd_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
