# Generated by Django 5.2.4 on 2025-07-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_certificate_file1_cleared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file1_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file1_psd_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file2_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file2_psd_cleared',
        ),
    ]
