# Generated by Django 5.2.4 on 2025-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_remove_certificate_file1_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file1_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file1_psd_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file2_psd_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file3_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
