# Generated by Django 5.2.4 on 2025-07-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_certificate_file1_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='clear_file1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='clear_file1_psd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='clear_file2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='clear_file2_psd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='clear_file3',
            field=models.BooleanField(default=False),
        ),
    ]
