# Generated by Django 5.2.4 on 2025-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_certificate_clear_file1_certificate_clear_file1_psd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'ordering': ['full_name'], 'verbose_name': 'Аудитор', 'verbose_name_plural': 'Аудиторы'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file1_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file1_psd_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file2_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file2_psd_cleared',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file3_cleared',
        ),
        migrations.AlterField(
            model_name='auditor',
            name='generated_audit_image',
            field=models.ImageField(blank=True, null=True, upload_to='audit_images/', verbose_name='Сгенерированное изображение аудита'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
