# Generated by Django 5.2.4 on 2025-07-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_alter_auditor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='generated_permission',
        ),
    ]
