# Generated by Django 5.2.4 on 2025-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_remove_certificate_generated_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='generated_permission',
            field=models.FileField(blank=True, null=True, upload_to='permissions/', verbose_name='Сгенерированное разрешение'),
        ),
    ]
