# Generated by Django 5.2.4 on 2025-07-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_certificate_generated_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='generated_permission',
        ),
    ]
