# Generated by Django 5.2.3 on 2025-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0019_remove_certificate_generated_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="identifier_type",
            field=models.CharField(
                choices=[("inn", "ИНН"), ("unp", "УНП")],
                default="inn",
                max_length=3,
                verbose_name="Тип идентификатора",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="identifier_value",
            field=models.CharField(
                default="", max_length=255, verbose_name="Номер идентификатора"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="inn",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ИНН организации"
            ),
        ),
    ]
