# Generated by Django 5.2.3 on 2025-09-15 12:51

from django.db import migrations


def migrate_inn_to_identifier(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    for certificate in Certificate.objects.all():
        if certificate.inn and not certificate.identifier_value:
            certificate.identifier_value = certificate.inn
            certificate.identifier_type = 'inn'
            certificate.save()


def reverse_migrate_inn_to_identifier(apps, schema_editor):
    Certificate = apps.get_model('certificates', 'Certificate')
    for certificate in Certificate.objects.all():
        if certificate.identifier_value and certificate.identifier_type == 'inn':
            certificate.inn = certificate.identifier_value
            certificate.save()


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0020_add_identifier_fields"),
    ]

    operations = [
        migrations.RunPython(
            migrate_inn_to_identifier,
            reverse_migrate_inn_to_identifier
        ),
    ]
