# Generated by Django 5.2.3 on 2025-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0021_migrate_inn_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="generated_audit",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_audits/",
                verbose_name="Аудит (без подписей)",
            ),
        ),
        migrations.AddField(
            model_name="auditor",
            name="generated_audit_signed",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_audits/",
                verbose_name="Аудит (с подписями)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_certificate",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_certificates/",
                verbose_name="Сертификат (без подписей)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_certificate_signed",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_certificates/",
                verbose_name="Сертификат (с подписями)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_permission",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_permissions/",
                verbose_name="Разрешение (без подписей)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_permission_signed",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="generated_permissions/",
                verbose_name="Разрешение (с подписями)",
            ),
        ),
    ]
