# Generated by Django 5.2.3 on 2025-10-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0022_add_generated_certificate_images"),
    ]

    operations = []
