# Generated by Django 5.2.3 on 2025-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0029_migrate_iso_standard_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-certificate_number_part"],
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
            },
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="certification_area",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="quality_management_system",
            field=models.TextField(verbose_name="Область сертификации"),
        ),
    ]
